### ISSUE TITLE
could not import zoo

### ISSUE THREAD

**Issue by mammadmaheri7** [neuralmagic/sparsezoo#484]
Hi,

I encounter an error when I try to import ScheduledModifierManager:

versions:
sparsezoo-nightly: 1.5.0.20230531
sparseml-nightly: 1.5.4.20240501

code:
from sparseml.pytorch.optim import ScheduledModifierManager

log of error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparseml_nightly-1.5.4.20240501-py3.9.egg/sparseml/__init__.py", line 33, in <module>
    from .framework import (
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparseml_nightly-1.5.4.20240501-py3.9.egg/sparseml/framework/__init__.py", line 22, in <module>
    from .info import *
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparseml_nightly-1.5.4.20240501-py3.9.egg/sparseml/framework/info.py", line 55, in <module>
    from sparseml.sparsification.info import SparsificationInfo
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparseml_nightly-1.5.4.20240501-py3.9.egg/sparseml/sparsification/__init__.py", line 22, in <module>
    from .analyzer import *
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparseml_nightly-1.5.4.20240501-py3.9.egg/sparseml/sparsification/analyzer.py", line 26, in <module>
    from sparseml.optim import default_pruning_sparsities_loss
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparseml_nightly-1.5.4.20240501-py3.9.egg/sparseml/optim/__init__.py", line 23, in <module>
    from .helpers import *
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparseml_nightly-1.5.4.20240501-py3.9.egg/sparseml/optim/helpers.py", line 35, in <module>
    from sparsezoo import Zoo
ImportError: cannot import name 'Zoo' from 'sparsezoo' (/rds/general/user/mm6322/home/anaconda3/envs/CAP_new_new/lib/python3.9/site-packages/sparsezoo_nightly-1.5.0.20230531-py3.9.egg/sparsezoo/__init__.py)

**Comment by mgoin** [comment]
Hey @mammadmaheri7 , those versions are from our 1.5 nightly version which is quite old at this point, and the nightly versions don't match exactly. Could you try upgrading them to the latest version or forcing them to match the same dated version?

**Comment by mammadmaheri7** [comment]
As I trying to reproduce the result of recent published paper, they've implemented their codes based on older version of sparsezoo and updating sparsezoo will end up inconstancy. So upgrading sparsezoo is not possible.

**Comment by mammadmaheri7** [comment]
Also, I've tried latest version of sparsezoo (1.7.0) but still I encountered the same error:

trace:

Traceback (most recent call last):
  File "one_shot_pruning.py", line 21, in <module>
    from sparseml.pytorch.optim import ScheduledModifierManager
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparseml-1.7.0-py3.8.egg/sparseml/__init__.py", line 33, in <module>
    from .framework import (
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparseml-1.7.0-py3.8.egg/sparseml/framework/__init__.py", line 22, in <module>
    from .info import *
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparseml-1.7.0-py3.8.egg/sparseml/framework/info.py", line 55, in <module>
    from sparseml.sparsification.info import SparsificationInfo
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparseml-1.7.0-py3.8.egg/sparseml/sparsification/__init__.py", line 22, in <module>
    from .analyzer import *
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparseml-1.7.0-py3.8.egg/sparseml/sparsification/analyzer.py", line 26, in <module>
    from sparseml.optim import default_pruning_sparsities_loss
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparseml-1.7.0-py3.8.egg/sparseml/optim/__init__.py", line 23, in <module>
    from .helpers import *
  File "/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparseml-1.7.0-py3.8.egg/sparseml/optim/helpers.py", line 35, in <module>
    from sparsezoo import Zoo
ImportError: cannot import name 'Zoo' from 'sparsezoo' (/rds/general/user/mm6322/home/anaconda3/envs/CAP_final/lib/python3.8/site-packages/sparsezoo-1.7.0-py3.8.egg/sparsezoo/__init__.py)

**Comment by bfineran** [comment]
Hi @mammadmaheri7 can you maybe start from a clean environment? It looks like the import that it's failing on is quite old (even before 1.5) and is not up to date with what is in the 1.5 branch even.  This also definitely should not be getting hit in 1.7 which leads me to believe there may be a local environment issue.  Maybe it's anaconda? Our testing is done only through pip.

see the updated import on the 1.5 branch: https://github.com/neuralmagic/sparseml/blob/28894c3fcd87ea7cfca5101189d0ffb2c64a3e6f/src/sparseml/optim/helpers.py#L35

**Comment by jeanniefinks** [comment]
Hi @mammadmaheri7 
We wanted to check in and see if the last comment was able to help you?
Thank you,
Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Closing as there has been no further activity.
Regards, Jeannie / Neural Magic
