### ISSUE TITLE
403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by shatak2012** [neuralmagic/sparsezoo#95]
**Describe the bug**
I am trying to search and download the models in sparsemodel zoo and running into authentication issue. Not sure what am I missing? Do I need to get some license/permission to be able to access the models in sparsezoo?

**Expected behavior**
Query/Download sparsezoo models for image classification should work without error 

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Windows
2. Python version [e.g. 3.7]: 3.6
3. SparseZoo version or commit hash [e.g. 0.1.0, `f7245c8`]: sparsezoo==0.3.1 
4. ML framework version(s) [e.g. torch 1.7.1]: NA
5. Other Python package versions [e.g. SparseML, DeepSparse, numpy, ONNX]: NA
6. Other relevant environment information [e.g. hardware, CUDA version]: NA

**To Reproduce**
I am running following command
sparsezoo search --domain cv --sub-domain classification

**Errors**

INFO:root:loading available models...
INFO:sparsezoo.requests.authentication:Obtaining new sparse zoo credentials token
Traceback (most recent call last):
  File "c:\anaconda\envs\python3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\envs\python3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\envs\python3.6\Scripts\sparsezoo.exe\__main__.py", line 7, in <module>
  File "c:\anaconda\envs\python3.6\lib\site-packages\sparsezoo\main.py", line 414, in main
    search(args)
  File "c:\anaconda\envs\python3.6\lib\site-packages\sparsezoo\main.py", line 357, in search
    page_length=args.page_length,
  File "c:\anaconda\envs\python3.6\lib\site-packages\sparsezoo\models\zoo.py", line 354, in search_models
    force_token_refresh=force_token_refresh,
  File "c:\anaconda\envs\python3.6\lib\site-packages\sparsezoo\objects\model.py", line 560, in search_models
    force_token_refresh=force_token_refresh,
  File "c:\anaconda\envs\python3.6\lib\site-packages\sparsezoo\requests\search.py", line 105, in search_model_get_request
    force_token_refresh=force_token_refresh,
  File "c:\anaconda\envs\python3.6\lib\site-packages\sparsezoo\requests\search.py", line 68, in search_get_request
    header = get_auth_header(force_token_refresh=force_token_refresh)
  File "c:\anaconda\envs\python3.6\lib\site-packages\sparsezoo\requests\authentication.py", line 148, in get_auth_header
    response.raise_for_status()
  File "c:\anaconda\envs\python3.6\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.neuralmagic.com/%5Cauth

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by jeanniefinks** [comment]
Hi @shatak2012 
Thank you for your thorough bug report. While we officially support Linux, your reporting the Windows issue helped us correct the issue per the linked PR (https://github.com/neuralmagic/sparsezoo/pull/96) Once the PR is merged, the updated code will be available our nightly builds at https://pypi.org/project/sparsezoo-nightly/ and then included with our next official release at the end of this month.
Cheers, Jeannie / Neural Magic
